language: go
go:
  - tip

install:
 - "go get -d -v ./..."
 - "go build -v ./..."

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ifuyivara"
  - git config --local user.email "ifuyivara@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file: "sidebreaker"
 skip_cleanup: true
