language: go
go:
  - tip

install:
 - "go get -d -v ./..."
 - "GOOS=windows GOARCH=amd64 go build -o sidebreaker-win-amd64.exe -v ./..."
 - "GOOS=linux GOARCH=arm go build -o sidebreaker-linux-amd64 -v ./..."
 - "GOOS=darwin GOARCH=amd64 go build -o sidebreaker-darwin-amd64 -v ./..."

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ifuyivara"
  - git config --local user.email "ifuyivara@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)"

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file: 
  - "sidebreaker-linux-amd64"
  - "sidebreaker-win-amd64.exe"
  - "sidebreaker-darwin-amd64"
 skip_cleanup: true
